DEBUG 2016-07-24 09:27:33,554: 	 Executing command: 'submit'
DEBUG 2016-07-24 09:27:33,555: 	 Found CRAB cache file /afs/cern.ch/user/a/aavkhadi/.crab3
DEBUG 2016-07-24 09:27:33,563: 	 Checking credentials
DEBUG 2016-07-24 09:27:33,564: 	 Found proxy file /tmp/x509up_u90315
DEBUG 2016-07-24 09:27:33,564: 	 Getting proxy life time left
DEBUG 2016-07-24 09:27:34,074: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -timeleft
 output : 604395

 error: 
 retcode : 0
DEBUG 2016-07-24 09:27:34,580: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -actimeleft
 output : 604394

 error: 
 retcode : 0
DEBUG 2016-07-24 09:27:34,580: 	 Proxy valid for 167:53:15 hours
INFO 2016-07-24 09:27:34,580: 	 Will use CRAB configuration file crab_config_bTagDijetV11_lowlumi.py
DEBUG 2016-07-24 09:27:34,581: 	 Loading CRAB configuration file.
DEBUG 2016-07-24 09:27:36,611: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-07-24 09:27:36,611: 	 Working area '/afs/cern.ch/user/a/aavkhadi/CMSSW_8_0_11/src/bbtoDijet/CRAB/crab_test_eff_bTagDijetV11_lowlumi/crab_eff_bTagDijetV11_lowlumi' already exists 
Please change the requestName in the config file
ERROR 2016-07-24 09:27:36,611: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/a/aavkhadi/CMSSW_8_0_11/src/bbtoDijet/CRAB/crab_test_eff_bTagDijetV11_lowlumi/crab_eff_bTagDijetV11_lowlumi' already exists 
Please change the requestName in the config file
DEBUG 2016-08-05 13:56:42,207: 	 Executing command: 'status'
DEBUG 2016-08-05 13:56:42,208: 	 Found CRAB cache file /afs/cern.ch/user/a/aavkhadi/.crab3
DEBUG 2016-08-05 13:56:42,217: 	 Checking credentials
DEBUG 2016-08-05 13:56:42,218: 	 Proxy file /tmp/x509up_u90315 not found
DEBUG 2016-08-05 13:56:42,218: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-05 13:56:46,435: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-05 13:56:46,942: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:56:46,942: 	 Error while checking proxy timeleft for /tmp/x509up_u90315
DEBUG 2016-08-05 13:56:47,348: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u90315 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:56:47,348: 	 Problems creating proxy.
ERROR 2016-08-05 13:56:47,348: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-05 13:56:48,425: 	 Executing command: 'status'
DEBUG 2016-08-05 13:56:48,425: 	 Found CRAB cache file /afs/cern.ch/user/a/aavkhadi/.crab3
DEBUG 2016-08-05 13:56:48,436: 	 Checking credentials
DEBUG 2016-08-05 13:56:48,437: 	 Proxy file /tmp/x509up_u90315 not found
DEBUG 2016-08-05 13:56:48,437: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-05 13:56:51,850: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-05 13:56:52,154: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:56:52,154: 	 Error while checking proxy timeleft for /tmp/x509up_u90315
DEBUG 2016-08-05 13:56:52,457: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u90315 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:56:52,458: 	 Problems creating proxy.
ERROR 2016-08-05 13:56:52,458: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-05 13:56:53,754: 	 Executing command: 'status'
DEBUG 2016-08-05 13:56:53,755: 	 Found CRAB cache file /afs/cern.ch/user/a/aavkhadi/.crab3
DEBUG 2016-08-05 13:56:53,759: 	 Checking credentials
DEBUG 2016-08-05 13:56:53,759: 	 Proxy file /tmp/x509up_u90315 not found
DEBUG 2016-08-05 13:56:53,759: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-05 13:57:00,177: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-05 13:57:00,481: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:57:00,481: 	 Error while checking proxy timeleft for /tmp/x509up_u90315
DEBUG 2016-08-05 13:57:00,784: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u90315 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u90315 (No such file or directory)

 retcode : 1
ERROR 2016-08-05 13:57:00,785: 	 Problems creating proxy.
ERROR 2016-08-05 13:57:00,785: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-05 17:37:54,580: 	 Executing command: 'submit'
DEBUG 2016-08-05 17:37:54,581: 	 Found CRAB cache file /afs/cern.ch/user/a/aavkhadi/.crab3
DEBUG 2016-08-05 17:37:54,589: 	 Checking credentials
DEBUG 2016-08-05 17:37:54,590: 	 Found proxy file /tmp/x509up_u90315
DEBUG 2016-08-05 17:37:54,590: 	 Getting proxy life time left
DEBUG 2016-08-05 17:37:55,095: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -timeleft
 output : 41055

 error: 
 retcode : 0
DEBUG 2016-08-05 17:37:55,601: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u90315 -actimeleft
 output : 41054

 error: 
 retcode : 0
DEBUG 2016-08-05 17:37:55,601: 	 Proxy valid for 11:24:15 hours
INFO 2016-08-05 17:37:55,601: 	 Will use CRAB configuration file crab_config_bTagDijetV11_HLT.py
DEBUG 2016-08-05 17:37:55,601: 	 Loading CRAB configuration file.
DEBUG 2016-08-05 17:37:57,758: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-05 17:37:57,760: 	 Working area '/afs/cern.ch/user/a/aavkhadi/CMSSW_8_0_11/src/bbtoDijet/CRAB/crab_test_bbtoDijetV11_HLT/crab_bbtoDijetV11_HLT' already exists 
Please change the requestName in the config file
ERROR 2016-08-05 17:37:57,760: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/a/aavkhadi/CMSSW_8_0_11/src/bbtoDijet/CRAB/crab_test_bbtoDijetV11_HLT/crab_bbtoDijetV11_HLT' already exists 
Please change the requestName in the config file
